input-ipc-server=/tmp/mpv-socket
stream-record=~/Videos/mpv-recordings
ytdl-format=bestvideo+bestaudio/best

# Auto-load external subtitles (same name, or in subfolders)
sub-auto=fuzzy
sub-file-paths=subs:subtitles:.
# Language priority
slang=en,eng,fa,per,persian
# Subtitle encoding fallback
sub-codepage=utf-8:utf-16:cp1256